name: Build BulbMan APK

on:
  push:
    branches:
      - main   # Change this if you want another branch
  workflow_dispatch:  # Keep manual trigger option

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip openjdk-17-jdk unzip git
          pip install --upgrade buildozer cython

      - name: Build APK
        working-directory: BulbManGame
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: BulbMan-APK
          path: BulbManGame/bin/*.apk
